# Generated by Django 5.1.1 on 2024-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=42)),
                ('hero_id', models.CharField(max_length=50)),
                ('rarity', models.IntegerField()),
                ('hero_rarity_index', models.CharField(max_length=100)),
                ('token_id', models.CharField(max_length=50)),
                ('season', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('tx_hash', models.CharField(max_length=66)),
                ('blocknumber', models.BigIntegerField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('picture', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('previous_rank', models.IntegerField()),
                ('is_player', models.BooleanField()),
                ('is_blue_verified', models.BooleanField()),
                ('default_profile_image', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('fast_followers_count', models.IntegerField()),
                ('favourites_count', models.BigIntegerField()),
                ('followers_count', models.BigIntegerField()),
                ('friends_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('media_count', models.IntegerField()),
                ('possibly_sensitive', models.BooleanField()),
                ('profile_banner_url', models.URLField(blank=True, max_length=500)),
                ('profile_image_url_https', models.URLField(blank=True, max_length=500)),
                ('has_banner', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statuses_count', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('player_address', models.CharField(blank=True, max_length=42)),
                ('can_be_packed', models.BooleanField()),
                ('previous_stars', models.IntegerField()),
                ('star_gain', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
