# Generated by Django 5.1.1 on 2024-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hero_player_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='can_be_packed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='default_profile_image',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='fast_followers_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='favourites_count',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='friends_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='has_banner',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='is_blue_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='listed_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='media_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='possibly_sensitive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='previous_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='previous_stars',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='profile_banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='profile_image_url_https',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='star_gain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='statuses_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
