# Generated by Django 5.1.1 on 2024-09-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_card_picture_alter_hero_can_be_packed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
