# Generated by Django 5.1.1 on 2024-10-01 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_hero_change_1_day_hero_change_7_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='current_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='fantasy_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='last_sale',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='tactic_image_prefix',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='CardSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('burnt', models.IntegerField()),
                ('total', models.IntegerField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_supplies', to='api.hero')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('rarity', models.CharField(max_length=50)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_prices', to='api.hero')),
            ],
        ),
        migrations.CreateModel(
            name='HighestBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('rarity', models.CharField(max_length=50)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bids', to='api.hero')),
            ],
        ),
    ]
