# Generated by Django 5.1.1 on 2024-10-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hero_current_rank_hero_fantasy_score_hero_last_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='volume',
            field=models.DecimalField(decimal_places=0, max_digits=40, null=True),
        ),
    ]
